### ISSUE TITLE
missing module in requirements.txt

### ISSUE THREAD

**Issue by kerolloz** [codassassin/voice-assistant#2]
![image](https://user-images.githubusercontent.com/36763164/127031980-84b0cb7e-77a4-4968-b6aa-e3de2bb8b3b9.png)

**Comment by codassassin** [comment]
![speechRecognition](https://user-images.githubusercontent.com/55107082/127103547-3a8eaa76-3858-42a9-a882-9d131c7f89ce.png)

**Comment by codassassin** [comment]
issue resolved
